/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.juegos.proyectofinal.UI;

/**
 *
 * @author calin
 */
public class TipoDeJuego extends javax.swing.JFrame {

    /**
     * Creates new form TipoDeJuego
     * @param numero
     */
    public TipoDeJuego(int numero) {
        initComponents();
        IniciarTipo(numero);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void IniciarTipo(int num){
      if (num == 0){
       TiposDama NuevaDama = new TiposDama();
       NuevaDama.setSize(200,200);
       NuevaDama.setLocation(100, 50);
       this.getContentPane().add(NuevaDama);
      }
      if (num == 1){
       TiposHanoi NuevoHanoi = new TiposHanoi();
       NuevoHanoi.setSize(200,200);
       NuevoHanoi.setLocation(100, 50);   
       this.getContentPane().add(NuevoHanoi);
      }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
